name: Build And Test

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        profile: [release, dev]

    name: Build And Test on ${{ matrix.os }} with profile ${{ matrix.profile }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      TARGET_DIR: ${{ matrix.profile == 'dev' && 'debug' || matrix.profile }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ matrix.os }}-${{ matrix.profile }}-cache

      - name: Update Package List (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: Install Dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y clang mold pkg-config libx11-dev \
            libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - name: Build
        run: cargo build --profile ${{ matrix.profile }}

      - name: Copy Assets Folder
        run: cp -r ./assets ./target/${{ env.TARGET_DIR }}/assets

      - name: Run Tests
        run: cargo test --profile ${{ matrix.profile }}

      - name: Remove Assets Folder from Target
        run: rm -rf ./target/${{ env.TARGET_DIR }}/assets