name: Build And Test

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        profile: [release, dev]

    name: Build And Test on ${{ matrix.os }} with profile ${{ matrix.profile }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Restore Cache
        uses: actions/cache@v5
        with:
          path: target
          key: ${{ matrix.os }}-${{ matrix.profile }}-cache
    
      - name: Update And Upgrade
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get upgrade

      - name: Install Dependencies
        if: ${{ matrix.os  == 'ubuntu-latest' }}
        run: sudo apt-get install clang mold pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - name: Build
        run: cargo build --profile ${{ matrix.profile }}

      - name: Run Tests
        run: cargo test --profile ${{ matrix.profile }}
