name: Publish To Pages

on:
  push:
    branches: [master]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-to-pages:
    name: Publish To Pages
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Restore Cache
        uses: actions/cache@v5
        with:
          path: target
          key: wasm-cache

      - name: Update And Upgrade
        run: sudo apt-get update && sudo apt-get upgrade

      - name: Install Dependencies
        run: sudo apt-get install clang pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - name: Install ToolChain
        run: rustup target install wasm32-unknown-unknown

      - name: Build
        run: cargo build --profile wasm-release --target wasm32-unknown-unknown

      - name: Install wasm-bindgen
        # Bevy doesn't suppport the latest version yet!
        run: cargo install wasm-bindgen-cli --version 0.2.121

      - name: Generate Files For The Web
        run: |
          mkdir ./web/wasm &&
          wasm-bindgen \
          --no-typescript \
          --target web \
          --out-dir ./web/wasm \
          --out-name "BorkedCraft" \
          ./target/wasm32-unknown-unknown/wasm-release/BorkedCraft.wasm

      - name: Copy Assets Folder
        run: |
            cp -r ./assets ./web/wasm/assets

      - name: Copy LICENSE File
        run: |
            cp ./LICENSE ./web/LICENSE

      - name: Install wasm-opt
        # run: CC=clang CXX=clang++ cargo install wasm-opt <- Uncomment incase build fails
        run: cargo install wasm-opt

      - name: Optimize Final Wasm File For Size
        run: wasm-opt -Oz -o ./web/wasm/BorkedCraft_bg.wasm ./web/wasm/BorkedCraft_bg.wasm

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Web Directory
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./web/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
